# SPDX-FileCopyrightText: 2026 Lukas Friedrich / Tippel
# SPDX-License-Identifier: Apache-2.0
"""Build the HTML/manifest fixtures for the document check.

Run with ``python tests/fixtures/documents/generate.py``.

Why these are generated rather than committed by hand: the manifests are signed
with the test CA in ``tests/fixtures/media/generate.py``, and an ECDSA signature
differs on every run, so the bytes are not reproducible and a committed pair would
drift the moment anything about signing changed.

The pairing is the point. A document that cannot embed a manifest is bound to an
external one by hashing the delivered bytes (C2PA 2.4 §A.7), so each case is a
document *and* the manifest that claims it — and ``tampered.html`` is the same
manifest with a document that changed by four characters afterwards.
"""

# ruff: noqa: T201 - a generator script reports what it wrote.

from __future__ import annotations

import io
import json
import sys
from pathlib import Path

_HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(_HERE.parent / "media"))

import c2pa  # noqa: E402
import generate as media  # type: ignore[import-not-found]  # noqa: E402 - path set above

_AI = "http://cv.iptc.org/newscodes/digitalsourcetype/trainedAlgorithmicMedia"
_CAMERA = "http://cv.iptc.org/newscodes/digitalsourcetype/digitalCapture"

#: A small, realistic generated page. The year is what `tampered.html` changes,
#: because a fact edited after signing is the failure an operator would actually
#: make: nothing about the page looks wrong afterwards.
PAGE = (
    '<!doctype html>\n<html lang="de">\n<head><meta charset="utf-8">\n'
    "<title>Bäckerei Mustermann</title>\n"
    '<link rel="c2pa-manifest" href="index.html.c2pa">\n</head>\n'
    "<body>\n<h1>Frisch gebacken seit 1932.</h1>\n"
    "<p>Unsere Backstube öffnet um sechs.</p>\n</body>\n</html>\n"
)


def _manifest(source_type: str) -> dict[str, object]:
    return {
        "claim_generator_info": [{"name": "markproof-fixtures", "version": "1"}],
        "title": "index.html",
        "format": "text/html",
        "assertions": [
            {
                "label": "c2pa.actions",
                "data": {"actions": [{"action": "c2pa.created", "digitalSourceType": source_type}]},
            },
            {
                "label": "c2pa.ai-disclosure",
                "data": {"modelType": "text", "humanOversightLevel": "prompt_guided"},
            },
        ],
    }


def _sign(document: bytes, source_type: str) -> bytes:
    """A detached manifest bound to these exact bytes.

    ``set_no_embed`` is what makes this possible at all: c2pa-rs refuses to embed
    into HTML, but it will hash the bytes and hand back a manifest that stands
    beside them — which is exactly the A.7 arrangement.
    """
    with media._builder_context():
        builder = c2pa.Builder(_manifest(source_type))
        builder.set_no_embed()
        sink = io.BytesIO()
        signed: bytes = builder.sign(media.build_signer(), "text/html", io.BytesIO(document), sink)
        return signed


def write() -> None:
    document = PAGE.encode("utf-8")

    (_HERE / "signed-valid.html").write_bytes(document)
    (_HERE / "signed-valid.html.c2pa").write_bytes(_sign(document, _AI))

    # Same manifest, document edited afterwards. Four characters, no visible
    # damage, and the provenance claim no longer holds.
    (_HERE / "tampered.html").write_bytes(document.replace(b"1932", b"1888"))

    wrong = document.replace(b"Mustermann", b"Musterfrau")
    (_HERE / "signed-wrong-type.html").write_bytes(wrong)
    (_HERE / "signed-wrong-type.html.c2pa").write_bytes(_sign(wrong, _CAMERA))

    (_HERE / "unsigned.html").write_bytes(
        document.replace(b'<link rel="c2pa-manifest" href="index.html.c2pa">\n', b"")
    )

    (_HERE / "MANIFEST.json").write_text(
        json.dumps(
            {
                "_comment": "Generated by generate.py. Signatures are not reproducible.",
                "c2pa_python": c2pa.version("c2pa-python"),
                "c2pa_rs_sdk": c2pa.sdk_version(),
                "cases": {
                    "signed-valid.html": "manifest bound to these bytes, AI source type -> PASS",
                    "tampered.html": "signed-valid's manifest, document edited after -> FAIL",
                    "signed-wrong-type.html": "validly bound, declares a camera capture -> FAIL",
                    "unsigned.html": "no manifest and no link to one -> FAIL",
                },
            },
            indent=2,
        )
        + "\n"
    )


if __name__ == "__main__":
    write()
    for path in sorted(_HERE.glob("*")):
        if path.name != "generate.py":
            print(f"  {path.name}  {path.stat().st_size} B")
