# SPDX-FileCopyrightText: 2026 Lukas Friedrich / Tippel
# SPDX-License-Identifier: Apache-2.0
"""The README has to stay true.

Documentation drifts silently: a command gets renamed, a config field changes,
and the first thing a new user copies is a line that does not work. These tests
run the README's own examples against the real surface, so the failure lands on
us instead of on them.
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest
from typer.testing import CliRunner

from markproof.cli import app
from markproof.config import load_config

_README = Path(__file__).resolve().parent.parent / "README.md"
_RUNNER = CliRunner()


def _readme() -> str:
    return _README.read_text(encoding="utf-8")


def _commands() -> list[str]:
    """Every `markproof …` invocation shown in the README."""
    found: list[str] = []
    for block in re.findall(r"```(?:bash|console)\n(.*?)```", _readme(), re.S):
        for line in block.splitlines():
            stripped = line.removeprefix("$ ").strip()
            if stripped.startswith("markproof "):
                found.append(stripped)
    return found


class TestCommands:
    def test_the_readme_shows_commands_at_all(self) -> None:
        assert _commands(), "no markproof invocations found — did the format change?"

    @pytest.mark.parametrize("command", _commands())
    def test_every_shown_subcommand_exists(self, command: str) -> None:
        """A command that does not exist is the worst possible first impression."""
        parts = command.split()
        # Walk to the first flag: everything before it is the subcommand path.
        subcommand = [p for p in parts[1:] if not p.startswith("-")]
        # Only the leading words are a subcommand path; arguments follow.
        candidates = subcommand[:2] if subcommand[:1] == ["rules"] else subcommand[:1]
        result = _RUNNER.invoke(app, [*candidates, "--help"])
        assert result.exit_code == 0, f"{' '.join(candidates)} is not a command: {result.output}"

    def test_no_command_uses_a_renamed_verb(self) -> None:
        """Guards the two renames that already bit us once."""
        text = _readme()
        assert "markproof check " not in text, "the command is `run`, not `check`"
        assert not re.search(r"markproof verify\s+[^-]", text), (
            "the command is `verify-report`, not `verify`"
        )


class TestExampleConfig:
    def test_the_example_config_validates(self) -> None:
        """The YAML in the README must load through the real config model."""
        match = re.search(r"```yaml\n# markproof\.yaml\n(.*?)```", _readme(), re.S)
        assert match, "the README no longer shows a markproof.yaml example"

        path = Path(__file__).resolve().parent / "_readme_example.yaml"
        try:
            path.write_text(match.group(1), encoding="utf-8")
            config = load_config(path)
        finally:
            path.unlink(missing_ok=True)

        assert config.target.probes, "example config declares no probes"
        assert config.rulepack

    def test_the_example_names_a_rulepack_that_ships(self) -> None:
        match = re.search(r"rulepack: ([\w.-]+)", _readme())
        assert match
        packaged = Path(__file__).resolve().parent.parent / "src" / "markproof" / "rulepacks"
        assert (packaged / f"{match.group(1)}.yaml").is_file()


class TestClaims:
    def test_every_rule_in_the_table_exists(self) -> None:
        """The README's rule table must not promise checks the build lacks."""
        from markproof.rules.schema import load_rulepack

        packaged = Path(__file__).resolve().parent.parent / "src" / "markproof" / "rulepacks"
        shipped = {r.id for r in load_rulepack(packaged / "art50-eu-2026.07.yaml").rules}
        # MPF-X-001 is generated by the engine, not declared in a rulepack.
        shipped.add("MPF-X-001")

        documented = set(re.findall(r"`(MPF-[A-Z]-\d{3})`", _readme()))
        assert documented, "the README no longer lists any rules"
        assert documented <= shipped, f"documented but not implemented: {documented - shipped}"

    def test_the_disclaimer_survives_edits(self) -> None:
        """The one sentence that must never be edited away."""
        assert "not legal advice" in _readme().lower()

    def test_alternatives_are_still_named(self) -> None:
        """Naming the competition is a deliberate credibility choice, not filler."""
        text = _readme()
        for project in ("art50-ci", "provcheck", "c2patool"):
            assert project in text, f"{project} is no longer mentioned"


class TestDisclaimerWording:
    """One wording, four places.

    ``docs/DISCLAIMER.md`` claims the two paragraphs stand word for word in the
    README and that the trademark one is the string the PDFs print. That claim
    used to be false in three small ways — an "or" for a "/", "belong to" for
    "are the property of", a sentence present on one side only. Small drift in
    the one document that makes wording an obligation is exactly the drift worth
    a test.
    """

    @staticmethod
    def _paragraphs(text: str) -> list[str]:
        return [re.sub(r"\s+", " ", p).strip() for p in text.strip().split("\n\n") if p.strip()]

    def _readme_disclaimer(self) -> list[str]:
        section = _readme().split("## Disclaimer", 1)[1].split("## Licence")[0]
        return self._paragraphs(section)

    def _disclaimer_quotes(self) -> list[str]:
        source = (_README.parent / "docs" / "DISCLAIMER.md").read_text(encoding="utf-8")
        blocks = re.findall(r"((?:^>.*\n?)+)", source, re.M)
        return [re.sub(r"\s+", " ", re.sub(r"^>\s?", "", b, flags=re.M)).strip() for b in blocks]

    def test_readme_and_disclaimer_agree_word_for_word(self) -> None:
        readme, disclaimer = self._readme_disclaimer(), self._disclaimer_quotes()
        assert len(disclaimer) >= 2, "docs/DISCLAIMER.md no longer quotes both paragraphs"
        assert readme[:2] == disclaimer[:2]

    def test_the_pdfs_print_the_same_trademark_paragraph(self) -> None:
        from markproof.report.pdf_reportlab import TRADEMARK_NOTICE

        assert self._readme_disclaimer()[0] == re.sub(r"\s+", " ", TRADEMARK_NOTICE).strip()

    def test_the_readme_points_at_the_full_scope_limits(self) -> None:
        assert "docs/DISCLAIMER.md" in _readme(), "the README no longer links the disclaimer"


class TestShippedExamples:
    """Every example config in the repo must load — they are what people copy."""

    @pytest.mark.parametrize(
        "relative",
        ["examples/markproof.yaml", "examples/demo-bot/markproof.yaml"],
    )
    def test_example_config_validates(self, relative: str) -> None:
        root = Path(__file__).resolve().parent.parent
        path = root / relative
        if not path.is_file():
            pytest.skip(f"{relative} not present")
        load_config(path)


class TestAttribution:
    """CC-BY travels with the material, not next to it."""

    def test_reports_carry_the_rulepack_attribution(self) -> None:
        """Findings quote the guidelines verbatim; the credit must go with them."""
        from markproof.report.model import build_report
        from markproof.rules.schema import load_rulepack

        root = Path(__file__).resolve().parent.parent
        rulepack = load_rulepack(root / "src" / "markproof" / "rulepacks" / "art50-eu-2026.07.yaml")
        report = build_report(
            target="t", rulepack=rulepack, findings=[], timestamp="2026-08-31T12:00:00+00:00"
        )
        assert "attribution" in report.rulepack
        assert "European Commission" in report.rulepack["attribution"]
        assert report.rulepack["license"] == "CC-BY-4.0"

    def test_the_summary_shows_it_too(self) -> None:
        from markproof.report.model import build_report
        from markproof.report.summary import render_summary
        from markproof.rules.schema import load_rulepack

        root = Path(__file__).resolve().parent.parent
        rulepack = load_rulepack(root / "src" / "markproof" / "rulepacks" / "art50-eu-2026.07.yaml")
        report = build_report(
            target="t", rulepack=rulepack, findings=[], timestamp="2026-08-31T12:00:00+00:00"
        )
        assert "European Commission" in render_summary(report)


class TestNoOverclaiming:
    """The README must not advertise a check the rulepack does not perform."""

    def test_emotion_recognition_is_not_advertised_as_checked(self) -> None:
        """It is Art. 50(3), it needs knowledge a probe cannot have, and no rule does it."""
        from markproof.rules.schema import load_rulepack

        root = Path(__file__).resolve().parent.parent
        rulepack = load_rulepack(root / "src" / "markproof" / "rulepacks" / "art50-eu-2026.07.yaml")
        categories = {
            getattr(rule.check, "category", None)
            for rule in rulepack.rules
            if hasattr(rule.check, "category")
        }
        text = _readme()
        if "emotion" not in categories:
            table = text[text.index("| Rule |") : text.index("**No LLM sits")]
            assert "emotion" not in table.lower(), (
                "the rule table advertises emotion recognition, which no rule checks"
            )


class TestTheFrontPageMatchesReality:
    """The README must not promise a state the repository is not in.

    Every one of these guards a mistake that was actually shipped: an install
    command for a package that was not on PyPI, an action pinned to a tag that did
    not exist, a link to a sibling repository that was never created, and a console
    transcript typed by hand rather than captured. Individually small; together they
    are the first thing a reader tests, and all four failed at once.
    """

    @staticmethod
    def _is_prerelease() -> bool:
        from markproof import __version__

        return any(marker in __version__ for marker in ("dev", "a", "b", "rc"))

    def test_no_pypi_install_before_there_is_a_pypi_release(self) -> None:
        """`pipx install markproof` must not appear while the version is a pre-release."""
        if not self._is_prerelease():
            pytest.skip("released version — the PyPI install line is correct")
        for command in _commands():
            assert not re.match(r"^markproof\s*$", command), command
        text = _readme()
        assert "pipx install markproof\n" not in text, (
            "the README offers a PyPI install, but this version is unreleased — "
            "use `pipx install git+https://github.com/Tippel-AI/markproof`"
        )

    def test_the_action_is_not_pinned_to_a_tag_that_does_not_exist(self) -> None:
        if not self._is_prerelease():
            pytest.skip("released version — a version tag is expected")
        pinned = re.findall(r"Tippel-AI/markproof/action@(\S+)", _readme())
        assert pinned, "the README no longer shows how to use the action"
        for ref in pinned:
            assert not re.match(r"^v\d", ref), (
                f"the action example pins {ref}, but no release tag exists yet — use @main"
            )

    def test_the_readme_links_no_repository_that_does_not_exist(self) -> None:
        """A dead link in the credibility paragraph costs more than it looks.

        Checked locally rather than over the network: CI must not go red because
        GitHub is slow. markproof is the only repository under this account, so any
        other Tippel-AI link is one somebody meant to create and did not.
        """
        linked = set(re.findall(r"github\.com/Tippel-AI/([A-Za-z0-9._-]+)", _readme()))
        assert linked <= {"markproof"}, (
            f"links to non-existent repositories: {sorted(linked - {'markproof'})}"
        )

    def test_the_transcript_is_the_reproducible_one(self) -> None:
        """A reader has to be able to run the thing that produced it."""
        blocks = re.findall(r"```console\n(.*?)```", _readme(), re.S)
        assert blocks, "the README no longer shows a console transcript"
        transcript = "\n".join(blocks)
        assert "demo-bot" in transcript, (
            "the transcript should come from examples/demo-bot, which a reader can run"
        )
        assert "examples/demo-bot" in _readme(), "the README does not link the demo bot"

    def test_the_transcript_does_not_show_a_report_the_command_cannot_write(self) -> None:
        """`run` writes a report only when --report-dir is passed."""
        for block in re.findall(r"```console\n(.*?)```", _readme(), re.S):
            if "report written to" not in block:
                continue
            invocations = [ln for ln in block.splitlines() if "markproof run" in ln]
            assert invocations, "a transcript shows a report with no run command"
            assert any("--report-dir" in ln for ln in invocations), (
                "the transcript shows a written report, but the command shown does not "
                "pass --report-dir, so no report would be written"
            )

    def test_the_optional_extras_the_rule_table_needs_are_named(self) -> None:
        """Three rules drive a browser. A reader must not learn that from a stack trace."""
        text = _readme()
        table = text[text.index("| Rule |") : text.index("**No LLM sits")]
        if "UI" in table or "page" in table:
            assert "markproof[ui]" in text, "the UI rules need the [ui] extra, unmentioned"
            assert "playwright install" in text, (
                "the [ui] extra ships a driver, not a browser — the second command is "
                "the one that catches people out"
            )
