# SPDX-FileCopyrightText: 2026 Lukas Friedrich / Tippel
# SPDX-License-Identifier: Apache-2.0
"""Scope: which obligations bind a target, and what silence means.

The field test that produced these rules ran markproof against three pages
generated by a real product. Every one returned the same two warnings — no AI
disclosure, no deep fake label — and neither obligation bound any of them: the
pages have no chat interface and carry stock photography. Any static website on
earth gets those two lines. A tool that says the same thing about every target
says nothing, and it teaches its users that warnings are noise.

So a target can now declare what binds it. The tests here pin the three states
that declaration has, because the value of the feature lives entirely in keeping
them apart:

* **undeclared** — the rule runs, exactly as before. Silence must never remove
  a check, or an omission becomes an opt-out nobody made.
* **declared inapplicable** — SKIP, visibly, naming whose claim it was.
* **declared applicable but unverifiable** — WARN. "We mark our text", "nothing
  was checked" and a green build is the silent pass this project exists to
  remove.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from markproof.checks.disclosure import PatternSet, load_pattern_set
from markproof.checks.labels import LabelPatternSet, load_label_set
from markproof.checks.synthid import SynthIdOutcome, SynthIdResult, WatermarkConfig
from markproof.config import MarkproofConfig
from markproof.report.model import build_report
from markproof.report.sign import sign_report, verify_report
from markproof.report.summary import render_summary
from markproof.rules.engine import Finding, Result, evaluate, exit_code_for
from markproof.rules.schema import (
    Applicability,
    Obligation,
    ProbeKind,
    Rulepack,
    load_rulepack,
)
from tests.helpers import make_evidence, make_turn, make_ui_evidence

_PKG = Path(__file__).resolve().parent.parent / "src" / "markproof"
_TIMESTAMP = "2026-08-31T12:00:00+00:00"

#: A watermark configuration that is structurally valid and never used to score
#: anything here: every test in this file either stops before the detector or
#: replaces it. The tokenizer is deliberately a name nothing will fetch — a test
#: that reached the network would have stopped testing routing.
_WATERMARK = WatermarkConfig(ngram_len=5, keys=[1, 2, 3], tokenizer="test-tokenizer-never-loaded")

#: A page with no chatbot, no deep fake and no disclosure — the shape of target
#: that produced two useless warnings before this feature existed.
_STATIC_PAGE = (
    "Frisch gebrüht. Unsere Bäckerei backt seit 1932 nach überlieferten Rezepten. "
    "Öffnungszeiten: Montag bis Samstag von 6 bis 18 Uhr. Kontakt und Anfahrt."
)


@pytest.fixture(scope="module")
def rulepack() -> Rulepack:
    return load_rulepack(_PKG / "rulepacks" / "art50-eu-2026.07.yaml")


@pytest.fixture(scope="module")
def patterns() -> dict[str, PatternSet]:
    return {"disclosure.de-en.yaml": load_pattern_set(_PKG / "patterns" / "disclosure.de-en.yaml")}


@pytest.fixture(scope="module")
def labels() -> dict[str, LabelPatternSet]:
    return {"labels.de-en.yaml": load_label_set(_PKG / "patterns" / "labels.de-en.yaml")}


def _run(
    rulepack: Rulepack,
    evidence: object,
    patterns: dict[str, PatternSet],
    labels: dict[str, LabelPatternSet],
    declared: dict[str, bool] | None = None,
    watermark: object = None,
) -> dict[str, Finding]:
    findings = evaluate(
        rulepack,
        [evidence],  # type: ignore[list-item]
        patterns,
        watermark,  # type: ignore[arg-type]
        labels,
        Applicability.model_validate(declared) if declared is not None else None,
    )
    return {f.rule_id: f for f in findings}


class TestTheDeclarationVocabulary:
    def test_silence_leaves_every_rule_running(self) -> None:
        """The default must not change what anyone already gets."""
        empty = Applicability()
        for obligation in Obligation:
            assert empty.applies(obligation)
            assert not empty.is_declared_applicable(obligation)

    def test_only_an_explicit_false_removes_a_rule(self) -> None:
        declared = Applicability.model_validate({"ai-interaction": False})
        assert not declared.applies(Obligation.AI_INTERACTION)
        assert declared.applies(Obligation.DEEPFAKE_LABELLING)

    def test_declared_applicable_is_not_the_same_as_undeclared(self) -> None:
        """The distinction the missing-configuration verdict rests on."""
        declared = Applicability.model_validate({"synthetic-text-marking": True})
        assert declared.is_declared_applicable(Obligation.SYNTHETIC_TEXT_MARKING)
        assert not declared.is_declared_applicable(Obligation.SYNTHETIC_MEDIA_MARKING)
        # …while both still run.
        assert declared.applies(Obligation.SYNTHETIC_MEDIA_MARKING)

    def test_an_unknown_obligation_is_a_loud_config_error(self) -> None:
        """A typo must not silently declare nothing."""
        with pytest.raises(ValueError, match="ai-interaction"):
            Applicability.model_validate({"ai-intraction": False})

    def test_every_shipped_rule_names_an_obligation(self, rulepack: Rulepack) -> None:
        """A rule that does not say which duty it serves cannot be scoped."""
        for rule in rulepack.rules:
            assert rule.obligation in Obligation


class TestTheFieldTestCase:
    """The three pages that started this. Both warnings should disappear."""

    def test_without_a_declaration_the_static_page_warns_twice(
        self,
        rulepack: Rulepack,
        patterns: dict[str, PatternSet],
        labels: dict[str, LabelPatternSet],
    ) -> None:
        """Today's behaviour, pinned — so the improvement is measurable."""
        findings = _run(rulepack, make_ui_evidence(_STATIC_PAGE), patterns, labels)
        assert findings["MPF-D-002"].result is Result.WARN
        assert findings["MPF-L-001"].result is Result.WARN

    def test_declaring_the_obligations_away_turns_both_into_skips(
        self,
        rulepack: Rulepack,
        patterns: dict[str, PatternSet],
        labels: dict[str, LabelPatternSet],
    ) -> None:
        findings = _run(
            rulepack,
            make_ui_evidence(_STATIC_PAGE),
            patterns,
            labels,
            {"ai-interaction": False, "deepfake-labelling": False},
        )
        assert findings["MPF-D-002"].result is Result.SKIP
        assert findings["MPF-L-001"].result is Result.SKIP

    def test_the_skip_says_whose_claim_it_was(
        self,
        rulepack: Rulepack,
        patterns: dict[str, PatternSet],
        labels: dict[str, LabelPatternSet],
    ) -> None:
        """Never a bare 'skipped' — the reader has to see it was asserted."""
        findings = _run(
            rulepack,
            make_ui_evidence(_STATIC_PAGE),
            patterns,
            labels,
            {"deepfake-labelling": False},
        )
        finding = findings["MPF-L-001"]
        assert "not applicable" in finding.message
        assert "deepfake-labelling" in finding.message
        assert finding.detail["outcome"] == "not_applicable"
        assert finding.detail["declared_by"] == "target configuration"

    def test_a_skipped_rule_is_still_reported(
        self,
        rulepack: Rulepack,
        patterns: dict[str, PatternSet],
        labels: dict[str, LabelPatternSet],
    ) -> None:
        """Dropping it from the list would make the declaration a mute button."""
        findings = _run(
            rulepack,
            make_ui_evidence(_STATIC_PAGE),
            patterns,
            labels,
            {"deepfake-labelling": False},
        )
        assert "MPF-L-001" in findings

    def test_declaring_one_obligation_away_leaves_the_others_alone(
        self,
        rulepack: Rulepack,
        patterns: dict[str, PatternSet],
        labels: dict[str, LabelPatternSet],
    ) -> None:
        findings = _run(
            rulepack, make_ui_evidence(_STATIC_PAGE), patterns, labels, {"ai-interaction": False}
        )
        assert findings["MPF-D-002"].result is Result.SKIP
        assert findings["MPF-L-001"].result is Result.WARN

    def test_declaring_it_applicable_keeps_the_finding(
        self,
        rulepack: Rulepack,
        patterns: dict[str, PatternSet],
        labels: dict[str, LabelPatternSet],
    ) -> None:
        """An operator who *does* run a chatbot still gets told it says nothing."""
        findings = _run(
            rulepack, make_ui_evidence(_STATIC_PAGE), patterns, labels, {"ai-interaction": True}
        )
        assert findings["MPF-D-002"].result is Result.WARN


class TestScopeDoesNotHideFailures:
    def test_a_real_failure_still_fails_when_its_duty_is_declared(
        self,
        rulepack: Rulepack,
        patterns: dict[str, PatternSet],
        labels: dict[str, LabelPatternSet],
    ) -> None:
        evidence = make_evidence(make_turn("neutral-opener", "Hallo! Wie kann ich helfen?"))
        findings = _run(rulepack, evidence, patterns, labels, {"ai-interaction": True})
        assert findings["MPF-D-001"].result is Result.FAIL
        assert exit_code_for(list(findings.values())) == 1

    def test_a_skipped_rule_never_sets_the_exit_code(
        self,
        rulepack: Rulepack,
        patterns: dict[str, PatternSet],
        labels: dict[str, LabelPatternSet],
    ) -> None:
        evidence = make_evidence(make_turn("neutral-opener", "Hallo! Wie kann ich helfen?"))
        findings = _run(rulepack, evidence, patterns, labels, {"ai-interaction": False})
        assert exit_code_for(list(findings.values())) == 0


class TestUnverifiableObligations:
    """Issue #15 — the silent green this feature exists to close."""

    def test_undeclared_and_unconfigured_stays_a_skip(
        self,
        rulepack: Rulepack,
        patterns: dict[str, PatternSet],
        labels: dict[str, LabelPatternSet],
    ) -> None:
        """Nothing was promised, so nothing is owed."""
        evidence = make_evidence(make_turn("neutral-opener", "Hallo, hier spricht eine KI."))
        finding = _run(rulepack, evidence, patterns, labels)["MPF-T-001"]
        assert finding.result is Result.SKIP
        assert finding.detail["declared_applicable"] == "not declared"

    def test_declared_applicable_and_unconfigured_warns(
        self,
        rulepack: Rulepack,
        patterns: dict[str, PatternSet],
        labels: dict[str, LabelPatternSet],
    ) -> None:
        """'We mark our text' plus 'nothing was checked' must not be green-and-quiet."""
        evidence = make_evidence(make_turn("neutral-opener", "Hallo, hier spricht eine KI."))
        finding = _run(rulepack, evidence, patterns, labels, {"synthetic-text-marking": True})[
            "MPF-T-001"
        ]
        assert finding.result is Result.WARN
        assert "declares a synthetic-text-marking obligation" in finding.message
        assert "was not verified" in finding.message

    def test_it_warns_rather_than_fails(
        self,
        rulepack: Rulepack,
        patterns: dict[str, PatternSet],
        labels: dict[str, LabelPatternSet],
    ) -> None:
        """markproof was not given the means to look — that is not proof of absence.

        An operator whose provider marks server-side has a real answer this tool
        cannot see. Failing on it would be the guess we refuse everywhere else.
        """
        evidence = make_evidence(make_turn("neutral-opener", "Hallo, hier spricht eine KI."))
        findings = _run(rulepack, evidence, patterns, labels, {"synthetic-text-marking": True})
        assert exit_code_for(list(findings.values())) == 0

    def test_declared_inapplicable_beats_declared_unconfigured(
        self,
        rulepack: Rulepack,
        patterns: dict[str, PatternSet],
        labels: dict[str, LabelPatternSet],
    ) -> None:
        """An obligation nobody has cannot have a hole in it."""
        evidence = make_evidence(make_turn("neutral-opener", "Hallo, hier spricht eine KI."))
        finding = _run(rulepack, evidence, patterns, labels, {"synthetic-text-marking": False})[
            "MPF-T-001"
        ]
        assert finding.result is Result.SKIP
        assert finding.detail["outcome"] == "not_applicable"


class TestTextMarkingOnRenderedPages:
    """Issue #16 — the check the field test could not reach."""

    def test_the_shipped_rule_now_covers_rendered_pages(self, rulepack: Rulepack) -> None:
        rule = next(r for r in rulepack.rules if r.id == "MPF-T-001")
        assert ProbeKind.UI in rule.applies_to

    def test_without_a_content_selector_it_declines_instead_of_guessing(
        self,
        rulepack: Rulepack,
        patterns: dict[str, PatternSet],
        labels: dict[str, LabelPatternSet],
    ) -> None:
        """Scoring a whole page averages template text with generated text."""
        finding = _run(
            rulepack,
            make_ui_evidence(_STATIC_PAGE),
            patterns,
            labels,
            watermark=_WATERMARK,  # present, so the missing piece is the selector
        )["MPF-T-001"]
        assert finding.result is Result.SKIP
        assert "content_selector" in finding.message
        assert "no generated-text region" in finding.message

    def test_a_declared_obligation_upgrades_that_to_a_warning(
        self,
        rulepack: Rulepack,
        patterns: dict[str, PatternSet],
        labels: dict[str, LabelPatternSet],
    ) -> None:
        finding = _run(
            rulepack,
            make_ui_evidence(_STATIC_PAGE),
            patterns,
            labels,
            {"synthetic-text-marking": True},
            watermark=_WATERMARK,
        )["MPF-T-001"]
        assert finding.result is Result.WARN

    def test_the_score_is_taken_from_the_region_not_the_page(
        self,
        rulepack: Rulepack,
        patterns: dict[str, PatternSet],
        labels: dict[str, LabelPatternSet],
        monkeypatch: pytest.MonkeyPatch,
    ) -> None:
        """Which text reaches the detector is the whole correctness question.

        Substituting the detector is the point rather than a shortcut: this
        asserts the routing, and the routing has to hold whether or not the
        optional SynthID stack is installed on the machine running the suite.
        """
        scored: list[str] = []

        def _record(text: str, check: object, config: object, **kwargs: object) -> SynthIdResult:
            scored.append(text)
            return SynthIdResult(
                outcome=SynthIdOutcome.WATERMARKED,
                detector="mean-g",
                score=0.81,
                token_count=140,
            )

        monkeypatch.setattr("markproof.rules.engine.detect_watermark", _record)

        region = "Generierter Fließtext, den das Modell geschrieben hat."
        evidence = make_ui_evidence(_STATIC_PAGE, content=region)
        finding = _run(rulepack, evidence, patterns, labels, watermark=_WATERMARK)["MPF-T-001"]

        assert scored == [region], "the detector must see the region, not the document"
        assert finding.result is Result.PASS

        # …and the finding cites the bytes that were actually scored.
        assert evidence.content_scope is not None
        assert finding.evidence_sha256 == (evidence.content_scope.sha256,)
        assert evidence.turns[0].response_sha256 not in finding.evidence_sha256
        assert finding.detail["content_selector"] == "article .body"

    def test_a_chat_probe_still_scores_the_response(
        self,
        rulepack: Rulepack,
        patterns: dict[str, PatternSet],
        labels: dict[str, LabelPatternSet],
        monkeypatch: pytest.MonkeyPatch,
    ) -> None:
        """The rendered-page path must not have changed the endpoint path."""
        scored: list[str] = []

        def _record(text: str, check: object, config: object, **kwargs: object) -> SynthIdResult:
            scored.append(text)
            return SynthIdResult(outcome=SynthIdOutcome.WATERMARKED, detector="mean-g", score=0.8)

        monkeypatch.setattr("markproof.rules.engine.detect_watermark", _record)

        reply = "Hallo, hier spricht eine KI. " * 12
        evidence = make_evidence(make_turn("neutral-opener", reply))
        finding = _run(rulepack, evidence, patterns, labels, watermark=_WATERMARK)["MPF-T-001"]

        assert scored == [reply]
        assert finding.detail["prompt_id"] == "neutral-opener"
        assert "content_selector" not in finding.detail


class TestTheDeclarationIsEvidence:
    """What separates this from a list of rules to switch off."""

    def test_the_report_records_what_was_declared(self, rulepack: Rulepack) -> None:
        report = build_report(
            target="t",
            rulepack=rulepack,
            findings=[],
            timestamp=_TIMESTAMP,
            applicability=Applicability.model_validate({"deepfake-labelling": False}),
        )
        assert report.applicability == {"deepfake-labelling": False}

    def test_no_declaration_leaves_the_report_shape_untouched(self, rulepack: Rulepack) -> None:
        """An empty declaration and no declaration are the same statement."""
        for declared in (None, Applicability()):
            report = build_report(
                target="t",
                rulepack=rulepack,
                findings=[],
                timestamp=_TIMESTAMP,
                applicability=declared,
            )
            assert report.applicability is None
            assert "applicability" not in report.to_canonical_dict()

    def test_the_signature_covers_the_declaration(self, rulepack: Rulepack) -> None:
        """Otherwise the scope of a green run could be rewritten afterwards."""
        from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey

        key = Ed25519PrivateKey.generate()
        signed = sign_report(
            build_report(
                target="t",
                rulepack=rulepack,
                findings=[],
                timestamp=_TIMESTAMP,
                applicability=Applicability.model_validate({"deepfake-labelling": False}),
            ),
            key,
        )
        assert verify_report(signed, None)[0]

        tampered = signed.model_copy(update={"applicability": {"deepfake-labelling": True}})
        valid, message = verify_report(tampered, None)
        assert not valid, "a rewritten scope must break the signature"
        assert message

    def test_the_summary_puts_the_scope_next_to_the_verdict(self, rulepack: Rulepack) -> None:
        """A reader judging a green run needs the scope in the same glance."""
        report = build_report(
            target="t",
            rulepack=rulepack,
            findings=[],
            timestamp=_TIMESTAMP,
            applicability=Applicability.model_validate(
                {"deepfake-labelling": False, "synthetic-text-marking": True}
            ),
        )
        summary = render_summary(report)
        assert "Declared scope" in summary
        assert "`deepfake-labelling`" in summary
        assert "`synthetic-text-marking`" in summary
        assert "operator's own statement" in summary

    def test_a_report_without_a_declaration_says_nothing_about_scope(
        self, rulepack: Rulepack
    ) -> None:
        report = build_report(target="t", rulepack=rulepack, findings=[], timestamp=_TIMESTAMP)
        assert "Declared scope" not in render_summary(report)


class TestConfigSurface:
    def test_the_block_parses_from_yaml_shaped_input(self) -> None:
        config = MarkproofConfig.model_validate(
            {
                "version": 1,
                "rulepack": "art50-eu-2026.07",
                "applicability": {"ai-interaction": False, "deepfake-labelling": False},
                "target": {
                    "name": "static site",
                    "probes": [{"id": "page", "type": "ui", "url": "https://example.invalid"}],
                },
            }
        )
        assert not config.applicability.applies(Obligation.AI_INTERACTION)

    def test_omitting_the_block_declares_nothing(self) -> None:
        config = MarkproofConfig.model_validate(
            {
                "version": 1,
                "rulepack": "art50-eu-2026.07",
                "target": {
                    "name": "static site",
                    "probes": [{"id": "page", "type": "ui", "url": "https://example.invalid"}],
                },
            }
        )
        assert config.applicability.root == {}
        assert config.applicability.applies(Obligation.DEEPFAKE_LABELLING)

    def test_a_blank_content_selector_is_rejected(self) -> None:
        """An empty selector matches nothing; it is a typo, not a wide scope."""
        with pytest.raises(ValueError, match="must not be blank"):
            MarkproofConfig.model_validate(
                {
                    "version": 1,
                    "rulepack": "art50-eu-2026.07",
                    "target": {
                        "name": "t",
                        "probes": [
                            {
                                "id": "page",
                                "type": "ui",
                                "url": "https://example.invalid",
                                "content_selector": "   ",
                            }
                        ],
                    },
                }
            )


class TestSchemaExport:
    def test_the_obligation_vocabulary_is_in_the_published_schema(self, rulepack: Rulepack) -> None:
        """Rulepack authors outside this repo need the list to be discoverable."""
        schema = json.dumps(Rulepack.model_json_schema())
        for obligation in Obligation:
            assert obligation.value in schema


class TestThePdfShowsScopeToo:
    """The PDF is the artefact somebody hands to an auditor."""

    def test_the_declaration_reaches_the_rendered_view(self, rulepack: Rulepack) -> None:
        from markproof.report.pdf_reportlab import report_view

        report = build_report(
            target="t",
            rulepack=rulepack,
            findings=[],
            timestamp=_TIMESTAMP,
            applicability=Applicability.model_validate({"deepfake-labelling": False}),
        )
        view = report_view(report.model_dump(mode="json", exclude_none=True))
        assert view.declared_scope == (("deepfake-labelling", False),)

    def test_a_report_without_one_renders_no_scope_claim(self, rulepack: Rulepack) -> None:
        from markproof.report.pdf_reportlab import report_view

        report = build_report(target="t", rulepack=rulepack, findings=[], timestamp=_TIMESTAMP)
        view = report_view(report.model_dump(mode="json", exclude_none=True))
        assert view.declared_scope == ()


class TestScopeProseReadsAsEnglish:
    """Small thing, but this sentence is the first line an auditor reads."""

    @staticmethod
    def _summary(rulepack: Rulepack, declared: dict[str, bool]) -> str:
        return render_summary(
            build_report(
                target="t",
                rulepack=rulepack,
                findings=[],
                timestamp=_TIMESTAMP,
                applicability=Applicability.model_validate(declared),
            )
        )

    def test_one_excluded_obligation_stays_singular(self, rulepack: Rulepack) -> None:
        text = self._summary(rulepack, {"deepfake-labelling": False})
        assert "no `deepfake-labelling` obligation, so the rules serving it" in text

    def test_several_excluded_obligations_are_joined_and_pluralised(
        self, rulepack: Rulepack
    ) -> None:
        text = self._summary(rulepack, {"deepfake-labelling": False, "ai-interaction": False})
        assert "no `ai-interaction` or `deepfake-labelling` obligations" in text
        assert "the rules serving them" in text

    def test_several_included_obligations_agree_with_their_verb(self, rulepack: Rulepack) -> None:
        text = self._summary(
            rulepack, {"synthetic-text-marking": True, "synthetic-media-marking": True}
        )
        assert "`synthetic-media-marking` or `synthetic-text-marking` apply" in text, (
            "a list of obligations takes a plural verb"
        )
